"""Creación de tabla persona

Revision ID: 58a9c61aaaf7
Revises: 
Create Date: 2022-03-05 14:30:12.271246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a9c61aaaf7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('pfname', sa.String(length=50), nullable=False),
    sa.Column('psname', sa.String(length=50), nullable=True),
    sa.Column('plname', sa.String(length=50), nullable=False),
    sa.Column('plname2', sa.String(length=50), nullable=True),
    sa.Column('prut', sa.Integer(), nullable=False),
    sa.Column('pphone', sa.Integer(), nullable=True),
    sa.Column('pdob', sa.Date(), nullable=False),
    sa.Column('pgender', sa.String(length=10), nullable=True),
    sa.Column('pphoto', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    # ### end Alembic commands ###
