"""Creacion de tabla usuario

Revision ID: c30af1fe568a
Revises: 58a9c61aaaf7
Create Date: 2022-03-05 14:32:20.766748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30af1fe568a'
down_revision = '58a9c61aaaf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('umail', sa.String(length=120), nullable=False),
    sa.Column('upass', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('umail')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
