"""relacion persona y usuario

Revision ID: cf8dd40a8d0b
Revises: c30af1fe568a
Create Date: 2022-03-05 14:44:31.611908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8dd40a8d0b'
down_revision = 'c30af1fe568a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_person_id', 'person', ['person_id'], ['pid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_person_id', type_='foreignkey')
        batch_op.drop_column('person_id')

    # ### end Alembic commands ###
