"""Rut unico

Revision ID: de0094610c9a
Revises: cf8dd40a8d0b
Create Date: 2022-03-11 18:28:10.388230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de0094610c9a'
down_revision = 'cf8dd40a8d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.create_unique_constraint("unique_prut", ['prut'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint("unique_prut", type_='unique')

    # ### end Alembic commands ###
