"""se agrega unique a rut

Revision ID: e2b46af526db
Revises: cf8dd40a8d0b
Create Date: 2022-03-11 18:26:40.602268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b46af526db'
down_revision = 'cf8dd40a8d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_prut', ['prut'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint('unique_prut', type_='unique')

    # ### end Alembic commands ###
